version: "3"

services:
  keycloak:
    build:
      context: .
      args: &keycloak-env-vars-needed-for-build
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: change_me
        KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: admin
        KC_HOSTNAME: localhost
        KC_DB: postgres
    command: start-dev
    environment:
      <<: *keycloak-env-vars-needed-for-build
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    depends_on:
      - postgres
    ports:
      - 8443:8443

  postgres:
    image: postgres
    volumes:
      - ./mount/db/keycloack-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432