version: "3"

services:
  keycloak:
    build:
      context: .
      args: &keycloak-env-vars-needed-for-build
        KC_DB: postgres
        KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
        KC_DB_USERNAME: ${POSTGRES_USER}
        KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
        KC_HOSTNAME: localhost
    command: start-dev
    environment:
      <<: *keycloak-env-vars-needed-for-build
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN_USERNAME}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      #JDBC_PARAMS: "ssl=true"
    depends_on:
      - postgres
    ports:
      - 8080:8080
      - 8443:8443

  postgres:
    image: postgres
    volumes:
      - ./mount/db/keycloack-db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432